hello:
  handler: src/handlers/swapi.run
  events:
    - httpApi:
        path: /swapi
        method: get

people:
  handler: src/handlers/people.run
  events:
    - httpApi:
        path: /
        method: post